spring:
  datasource:
    # mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8
    username: root
    password: 123456

  # Server HTTP port.
server:
  port: 9004
  tomcat:
    uri-encoding: utf-8